In [2]:
"""Topics : NumPy
Set 1:"""

'Topics : NumPy\n\nSet 1:\n•\tCreate a 3×3 array of all True Boolean values\n\n•\tExtract odd numbers from an array\n\n•\tReplace all odd numbers with -1\n\n•\tReverse columns of a 2D array\n\n•\tGet indices of elements greater than 5 [hint: check where method of numpy]\n\n•\tAccess last row - last column\n\nSet 2:\n•\tNormalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]\n\n•\tCreate a 5×5 array with 1 on border and 0 inside\n\n•\tCreate a random array of 10×10: perform stats (min, max, mean, std)\n\n•\tBroadcast a 1D array over a 2D array [all possible scenarios]\n\n•\tSort a 2D array by column 1 [hint: check method argsort()]\n\nSet 3:\n\n•\tFind common elements between two arrays [with and without using intersect1d, use isin() instead]\n\n•\tSubtract row mean from each row of a 2D array\n\n•\tGiven a 4×4 array, swap the first half rows with the second half rows\n\n•\tGiven a 1D array of random numbers, find the indices of t

In [4]:
import numpy as np

In [6]:
##•	Create a 3×3 array of all True Boolean values
arr=np.full(9,True).reshape(3,3)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [83]:
#•	Extract odd numbers from an array
arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
arr[arr%2==1]

array([ 5,  7,  9, 11, 13, 15])

In [12]:
#•	Replace all odd numbers with -1
arr[arr%2==1]=-1
arr

array([[-1,  6, -1,  8],
       [-1, 10, -1, 12],
       [-1, 14, -1, 16]])

In [48]:
#•	Reverse columns of a 2D array
arr=np.arange(5,17).reshape(3,4)
rev=np.flip(arr,axis=1)
rev

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [35]:
#•	Get indices of elements greater than 5 [hint: check where method of numpy]
arr=np.random.randint(1,10,9).reshape(3,3)
arr

array([[3, 8, 5],
       [9, 4, 3],
       [8, 9, 9]], dtype=int32)

In [39]:
row,col=np.where(arr>5)
np.stack((row,col),axis=1)

array([[0, 1],
       [1, 0],
       [2, 0],
       [2, 1],
       [2, 2]])

In [40]:
#•	Access last row - last column
arr

array([[3, 8, 5],
       [9, 4, 3],
       [8, 9, 9]], dtype=int32)

In [46]:
last=arr[-1,-1]
last

np.int32(9)

In [ ]:

•	Sort a 2D array by column 1 [hint: check method argsort()]

Set 3:
•	Find common elements between two arrays [with and without using intersect1d, use isin() instead]
•	Subtract row mean from each row of a 2D array
•	Given a 4×4 array, swap the first half rows with the second half rows
•	Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).
•	From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method)"""

In [49]:
#Set 2:
#•Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]


In [84]:
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
min_val = np.min(arr)
max_val = np.max(arr)
normalized_arr = (arr - min_val) / (max_val - min_val)
normalized_arr

array([[0.        , 0.09090909, 0.18181818, 0.27272727],
       [0.36363636, 0.45454545, 0.54545455, 0.63636364],
       [0.72727273, 0.81818182, 0.90909091, 1.        ]])

In [53]:
arr.flatten()

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [61]:
#•Create a 5×5 array with 1 on border and 0 inside
arr=np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
out = np.pad(arr, pad_width=1, constant_values=1)
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
#•Create a random array of 10×10: perform stats (min, max, mean, std)
arr1=np.random.random([10,10])
arr1

array([[5.65976522e-01, 8.66106814e-02, 7.93543638e-01, 7.87158057e-01,
        6.85371994e-01, 9.01834191e-02, 7.09583601e-01, 1.59498085e-02,
        6.39744599e-01, 2.34478332e-01],
       [8.45388486e-01, 1.39435556e-01, 9.97831656e-01, 8.62397578e-01,
        8.43494236e-02, 5.20941503e-01, 2.31327962e-01, 2.85999545e-02,
        8.87359496e-01, 1.88482636e-02],
       [2.55123523e-01, 4.97726707e-03, 1.25045208e-01, 2.63395295e-01,
        8.36318922e-01, 4.51059546e-01, 5.10277707e-01, 4.86837973e-01,
        1.61710786e-01, 1.03703104e-01],
       [7.92648588e-01, 8.20298018e-01, 8.51782842e-02, 3.82329029e-01,
        1.94008906e-01, 9.08886820e-01, 5.53717724e-01, 8.75780522e-01,
        8.48220551e-01, 5.50099563e-02],
       [5.79960347e-01, 2.93621265e-01, 8.68070977e-01, 3.16069283e-02,
        2.68161989e-01, 9.35621018e-01, 9.47236131e-01, 4.48448788e-01,
        8.48986072e-01, 3.34659038e-01],
       [7.74318799e-01, 4.04531534e-04, 9.58605342e-01, 9.35760352e-01,
   

In [77]:
np.min(arr1)

np.float64(0.00040453153441522005)

In [78]:
np.max(arr1)

np.float64(0.9999377611424651)

In [79]:
np.mean(arr1)

np.float64(0.4782322542734759)

In [80]:
np.std(arr1)

np.float64(0.31423614280919066)

In [85]:
#•Broadcast a 1D array over a 2D array [all possible scenarios]
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
arr2=np.array([1,3,5,6])
arr2

array([1, 3, 5, 6])

In [87]:
arr+arr2

array([[ 6,  9, 12, 14],
       [10, 13, 16, 18],
       [14, 17, 20, 22]])

In [89]:
arr3=np.array([[4],[5],[6]])
arr3

array([[4],
       [5],
       [6]])

In [90]:
arr+arr3

array([[ 9, 10, 11, 12],
       [14, 15, 16, 17],
       [19, 20, 21, 22]])

In [91]:
#•	Sort a 2D array by column 1 [hint: check method argsort()]
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
srt=np.argsort(arr,axis=1)
srt

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])