In [1]:
"""Name: Ashish Sameer Mulani
    PRN: 260240128007
    Name: Pranita Popat Lad
    PRN: 260240128028"""

'Name: Ashish Sameer Mulani\n    PRN: 260240128007\n    Name: Pranita Popat Lad\n    PRN: 260240128028'

In [ ]:
                                                       #Assignment 3

In [3]:
"""Topics : NumPy
Set 1:"""

'Topics : NumPy\nSet 1:'

In [4]:
import numpy as np

In [5]:
##•	Create a 3×3 array of all True Boolean values
arr=np.full(9,True).reshape(3,3)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
#•	Extract odd numbers from an array
arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
arr[arr%2==1]

array([ 5,  7,  9, 11, 13, 15])

In [8]:
#•	Replace all odd numbers with -1
arr[arr%2==1]=-1
arr

array([[-1,  6, -1,  8],
       [-1, 10, -1, 12],
       [-1, 14, -1, 16]])

In [9]:
#•	Reverse columns of a 2D array
arr=np.arange(5,17).reshape(3,4)
rev=np.flip(arr,axis=1)
rev

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [10]:
#•	Get indices of elements greater than 5 [hint: check where method of numpy]
arr=np.random.randint(1,10,9).reshape(3,3)
arr

array([[8, 8, 7],
       [3, 4, 4],
       [7, 3, 2]], dtype=int32)

In [11]:
row,col=np.where(arr>5)
np.stack((row,col),axis=1)

array([[0, 0],
       [0, 1],
       [0, 2],
       [2, 0]])

In [12]:
#•	Access last row - last column
arr

array([[8, 8, 7],
       [3, 4, 4],
       [7, 3, 2]], dtype=int32)

In [13]:
last=arr[-1,-1]
last

np.int32(2)

In [14]:
#Set 2:
#•Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]


In [15]:
arr

array([[8, 8, 7],
       [3, 4, 4],
       [7, 3, 2]], dtype=int32)

In [16]:
min_val = np.min(arr)
max_val = np.max(arr)
normalized_arr = (arr - min_val) / (max_val - min_val)
normalized_arr

array([[1.        , 1.        , 0.83333333],
       [0.16666667, 0.33333333, 0.33333333],
       [0.83333333, 0.16666667, 0.        ]])

In [17]:
arr.flatten()

array([8, 8, 7, 3, 4, 4, 7, 3, 2], dtype=int32)

In [18]:
#•Create a 5×5 array with 1 on border and 0 inside
arr=np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
out = np.pad(arr, pad_width=1, constant_values=1)
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#•Create a random array of 10×10: perform stats (min, max, mean, std)
arr1=np.random.random([10,10])
arr1

array([[0.14900108, 0.69991303, 0.40843011, 0.24597575, 0.57299369,
        0.65605086, 0.27491753, 0.83414535, 0.05648158, 0.74350204],
       [0.38770309, 0.9507527 , 0.74146906, 0.66165688, 0.31970337,
        0.55511073, 0.10324398, 0.55503144, 0.01501134, 0.03053342],
       [0.74032306, 0.1182886 , 0.99641166, 0.45862976, 0.2082224 ,
        0.79400656, 0.58353744, 0.8160362 , 0.56112827, 0.32622584],
       [0.87109366, 0.10364726, 0.87951497, 0.86583816, 0.95461314,
        0.32956065, 0.81079618, 0.11279261, 0.03600879, 0.97662484],
       [0.97851883, 0.63122409, 0.82594297, 0.93373638, 0.08880066,
        0.75937481, 0.63568992, 0.22128765, 0.81372046, 0.00618271],
       [0.97007529, 0.79614688, 0.42698565, 0.65514187, 0.35074072,
        0.57310479, 0.10316538, 0.81567537, 0.98651442, 0.87664506],
       [0.30788707, 0.0179434 , 0.00348325, 0.35463218, 0.8334801 ,
        0.13692933, 0.33934953, 0.28677084, 0.58229243, 0.88049845],
       [0.09523497, 0.11668032, 0.6045011

In [21]:
np.min(arr1)

np.float64(0.0034832519759729896)

In [22]:
np.max(arr1)

np.float64(0.9964116637611501)

In [23]:
np.mean(arr1)

np.float64(0.5025740574714738)

In [24]:
np.std(arr1)

np.float64(0.30482535165670177)

In [28]:
#•Broadcast a 1D array over a 2D array [all possible scenarios]
arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
arr2=np.array([1,3,5,6])
arr2

array([1, 3, 5, 6])

In [30]:
arr+arr2

array([[ 6,  9, 12, 14],
       [10, 13, 16, 18],
       [14, 17, 20, 22]])

In [31]:
arr3=np.array([[4],[5],[6]])
arr3

array([[4],
       [5],
       [6]])

In [32]:
arr+arr3

array([[ 9, 10, 11, 12],
       [14, 15, 16, 17],
       [19, 20, 21, 22]])

In [50]:
#•	Sort a 2D array by column 1 [hint: check method argsort()]
arr=np.random.randint(10,22,9).reshape(3,3)
arr

array([[19, 11, 18],
       [18, 20, 15],
       [20, 10, 17]], dtype=int32)

In [52]:
sort = arr[arr[:,1].argsort()]
sort

array([[20, 10, 17],
       [19, 11, 18],
       [18, 20, 15]], dtype=int32)

In [ ]:
#Set 3:
#•Find common elements between two arrays [with and without using intersect1d, use isin() instead]

In [37]:
arr1 = np.array([0, 10, 20, 40, 60, 10])
arr2 = np.array([10, 30, 40, 50])
arr1


array([ 0, 10, 20, 40, 60, 10])

In [38]:
arr2

array([10, 30, 40, 50])

In [47]:
#Intersected
common = np.intersect1d(arr1,arr2)
common

array([10, 40])

In [40]:
mask=np.isin(arr1, arr2)
mask

array([False,  True, False,  True, False,  True])

In [41]:
common=arr1[mask]
unique=np.unique(common)
unique

array([10, 40])

In [ ]:
#•Subtract row mean from each row of a 2D array

In [83]:
arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [85]:
r_mean=arr.mean(axis=1,keepdims=True)
new_arr=arr-r_mean
new_arr

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [ ]:
#•Given a 4×4 array, swap the first half rows with the second half rows

In [63]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
arr = np.roll(arr,2,axis=0)
arr

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
#•Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).

In [72]:
arr=np.random.randint(10,42,9).reshape(3,3)
arr

array([[33, 41, 23],
       [35, 37, 35],
       [21, 20, 24]], dtype=int32)

In [73]:
idx = np.argsort(arr, axis=None)
sorted_arr = arr.flatten()[idx]

n = 5
res = sorted_arr[-n:]
res

array([33, 35, 35, 37, 41], dtype=int32)

In [ ]:
#From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method)"""

In [86]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [88]:
unique_rows = np.unique(arr, axis=0)
unique_rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])