In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [4]:
arr=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
arr.astype(float)

array([1., 2., 3., 4., 5., 6., 7.])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(7,)

In [8]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr.ndim

1

In [10]:
arr.dtype

dtype('int64')

In [15]:
arr=arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
arr.shape

(2, 5)

In [18]:
zeros=np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
ones=np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr_b=np.full(9,True).reshape(3,3)
arr_b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
arr_r=np.random.random([3,3])
arr_r

array([[0.0739533 , 0.91155422, 0.70891264],
       [0.17670294, 0.15049711, 0.85868859],
       [0.52443507, 0.81437746, 0.53165166]])

In [26]:
arr_rd=np.random.randint(5,15,12) #start,end,total values
arr_rd

array([10,  6, 13,  6,  9,  9,  5,  5,  6,  7,  7, 13], dtype=int32)

In [34]:
arr_rd=np.random.randint(5,15,12).reshape(3,4)
arr_rd

array([[ 9, 11, 12, 12],
       [10,  8,  6, 12],
       [ 5,  6, 12,  7]], dtype=int32)

In [28]:
arr_l=np.linspace(2,20,10) #start end no.req
arr_l

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [30]:
arr_l=np.linspace(3,20,6)
arr_l

array([ 3. ,  6.4,  9.8, 13.2, 16.6, 20. ])

In [36]:
empty_a=np.empty([2,3]) #provide already available array
empty_a

array([[ 3. ,  6.4,  9.8],
       [13.2, 16.6, 20. ]])

In [32]:
id_a=np.identity(3)
id_a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
arr_rd.astype(float)

array([[ 9., 11., 12., 12.],
       [10.,  8.,  6., 12.],
       [ 5.,  6., 12.,  7.]])

In [41]:
empty_a=np.empty([3,4]) 
empty_a

array([[ 9., 11., 12., 12.],
       [10.,  8.,  6., 12.],
       [ 5.,  6., 12.,  7.]])

In [42]:
arr_rd

array([[ 9, 11, 12, 12],
       [10,  8,  6, 12],
       [ 5,  6, 12,  7]], dtype=int32)