In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [15]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
for e in arr:
    print(e)

[0 1 2]
[3 4 5]
[6 7 8]


In [17]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8


In [18]:
np.ravel(arr) #

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2=np.array([[11,12,13,14],[15,16,17,18]])
arr2

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [21]:
np.hstack([arr1,arr2])  #rows adds of both array

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [22]:
np.vstack([arr1,arr2])  #arr add after another

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [23]:
np.repeat(arr,2)  #each element by given time

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8])

In [24]:
arr= np.array([2,3])
arr

array([2, 3])

In [25]:
np.repeat(arr, (1,2))  #each index element by given time

array([2, 3, 3])

In [26]:
arr= np.array([[2,3],[4,5]])
arr

array([[2, 3],
       [4, 5]])

In [27]:
np.repeat(arr,(1,2,2,3))  #each index element by given time

array([2, 3, 3, 4, 4, 5, 5, 5])

In [28]:
arr= np.array([2,3])
arr

array([2, 3])

In [29]:
np.tile(arr, 2)   #add arr duplicate

array([2, 3, 2, 3])

In [30]:
arr=np.insert(arr, 1, 4)  #index,value
arr

array([2, 4, 3])

In [31]:
arr1=np.array([3,4])   
np.concatenate([arr, arr1])  #merge two arr

array([2, 4, 3, 3, 4])