In [1]:
import numpy as np

In [2]:
arr = np.arange(10,22).reshape(3,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [3]:
arr+3

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [4]:
arr*3

array([[30, 33, 36, 39],
       [42, 45, 48, 51],
       [54, 57, 60, 63]])

In [5]:
arr/3

array([[3.33333333, 3.66666667, 4.        , 4.33333333],
       [4.66666667, 5.        , 5.33333333, 5.66666667],
       [6.        , 6.33333333, 6.66666667, 7.        ]])

In [6]:
arr[arr>15]

array([16, 17, 18, 19, 20, 21])

In [7]:
arr1=np.array([1,2,3,4])
arr+arr1

array([[11, 13, 15, 17],
       [15, 17, 19, 21],
       [19, 21, 23, 25]])

In [9]:
arr2 = np.array([[10],[20],[30]])
arr2

array([[10],
       [20],
       [30]])

In [10]:
arr+arr2

array([[20, 21, 22, 23],
       [34, 35, 36, 37],
       [48, 49, 50, 51]])

In [11]:
arr1= arr1.reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [12]:
arr+arr1

ValueError: operands could not be broadcast together with shapes (3,4) (2,2) 

In [13]:
def find_square(num):
    return num*num

sq = np.vectorize(find_square)
arr_new = sq(arr1)
arr_new

array([[ 1,  4],
       [ 9, 16]])